### ISSUE TITLE
The app needs to show something when the list is empty

### ISSUE THREAD

**Issue by ZhangYiJiang** [CS2103AUG2016-W10-C4/main#119]
Showing the user an empty list is bad. There are two reasons why the list may be empty - 
1. The current filter filtered out everything - in which case the user may have made a typo (if they were using `find`), or they simply do not have any tasks that fulfil the criteria, in which case suggest another view 
2. The user has no tasks. Displaying an onboarding message encouraging them to start using the app (if they were using the app first time), or congratulating them on completing all their tasks may be appropriate here. 

For a first iteration simply show a message in each of the two situations is good. We can then iterate and see if we can easily distinguish between the other scenarios and display more nuanced messages.

**Comment by cricketer94** [comment]
Closed by #191
