### ISSUE TITLE
HighlightTaskEvent and ExpandCollapseTaskEvent need some sort of state information

### ISSUE THREAD

**Issue by cricketer94** [CS2103AUG2016-W10-C4/main#162]
Basically if edit the same task twice, the highlight becomes dimmed. 
E.g. Edit 1 /d tomorrow -> Task gets highlighted
Edit 1 /d today -> Task still has distinction from rest but it is no longer highlighted

Same thing if I happen to carry out changes to task details twice, sometimes details get hidden:
e.g. 
Edit /m Desc 1 -> Task highlighted and new description is shown
Edit /m desc 2 -> Task dimmed highlight + description is hidden even though it was edited

Possibly can attach boolean params to specify to UI when the events are meant to be a toggle and when it  is supposed to match the state specified

**Comment by xdrawks** [comment]
I'm fixing the HighlightTaskEvent bug in the tests
