### ISSUE TITLE
Automated test inconsistencies 

### ISSUE THREAD

**Issue by ZhangYiJiang** [CS2103AUG2016-W10-C4/main#171]
Automated tests sometimes fails. This meta issue tracks all of the problems 

- [x] `NullPointerException` at ` seedu.todo.ui.view.TodoListView.scrollAndSelect(TodoListView.java:111)` 
- [x] `testEventCompleted` sometimes fails because it relies on a separate thread 
- [x] `testPreviewAddCommand` - fails intermittently 
- [x] Some of the GUI tests uses randomly generated tests, which means on very rare occasions some branches will randomly be not reached

**Comment by xdrawks** [comment]
`NullPointerException` at `seedu.todo.ui.view.TodoListView.scrollAndSelect(TodoListView.java:111)`:
To deprecate this method and use index instead.

**Comment by ZhangYiJiang** [comment]
`testEventCompleted` use a sleep timer of 50ms now. Please report here if this test failure is observed again.

**Comment by xdrawks** [comment]
There seems to be a modifying Ui elements on non-ui thread bug with some exit command. Refer to the ss in the telegram chat
