### ISSUE TITLE
Integrate Checker framework into project 

### ISSUE THREAD

**Issue by ZhangYiJiang** [CS2103AUG2016-W10-C4/main#24]
Checker is a compile time static analysis tool that uses annotations like `@nonnull` and `@regex` to add guarantees to the code. This should be very helpful in avoiding `NullPointerException`s in the future. 
- Eclipse plugin: http://types.cs.washington.edu/checker-framework/eclipse 
- Gradle integration: http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#gradle

**Comment by ZhangYiJiang** [comment]
Just tried to do this. Two things 

1. Eclipse hangs when trying to refresh dependencies after I added Checker to Gradle config 
2. Executing compile generates 100 warnings and 8 errors. 

This doesn't look too good to be honest

**Comment by li-kai** [comment]
Checker framework is not being implemented due to difficulties listed by Yi Jiang.
