### ISSUE TITLE
Create human readable duration and relative date functions 

### ISSUE THREAD

**Issue by ZhangYiJiang** [CS2103AUG2016-W10-C4/main#28]
For the UI we need to show friendly duration and relative dates. Use cases: 

- [x] Convert a short datetime range to duration for events - eg. "2016-10-07T08:00" + "2016-10-07T10:00" -> "2 hours" or "2h"
- [x] Convert a datetime to a human readable relative time, useful for deadlines and showing upcoming or recently passed events, eg. "in 10 hours", "5 min ago", etc.

Consider switching to absolute datetime for dates are past some arbitrary number (eg. 24 hours), because it's hard to related to "in 4 days, 3 hours" vs. "12 Oct, 9pm". Remember to keep in mind the level of precision needed (eg. "1 hour" vs "45 min"). Also remember to use the most compact format possible - drop year if the year is the same as the current one, use short month names, etc.

**Comment by xdrawks** [comment]
@ZhangYiJiang "in 2 hours" (rounded closer to the deadline) or "in 2 hours 43 minutes" preferred?

**Comment by ZhangYiJiang** [comment]
In terms of resolution, I think it would be best stick to the largest unit (1d for more than 24h, 1h for more than 60min, etc.). For rounding, I would say use normal rounding rules (90+ min becomes 2h, below that becomes 1h, etc.)

**Comment by xdrawks** [comment]
http://stackoverflow.com/questions/24491260/mocking-time-in-java-8s-java-time-api to mock a fake current time

**Comment by xdrawks** [comment]
For ease of implementation, I'm rounding off closer to the deadline time rather than rounding off at the halfway mark

**Comment by xdrawks** [comment]
- [ ]  Left with events "getEventTimeText"
