### ISSUE TITLE
Embed custom font for cross platform support

### ISSUE THREAD

**Issue by xdrawks** [CS2103AUG2016-W10-C4/main#37]

**Comment by ZhangYiJiang** [comment]
For reference: https://github.com/CS2103AUG2016-W10-C4/addressbook-level3/commit/0b5d2155eaec4d94ec88d3cf0f48d9e14a831eec (although I wouldn't recommend Source Pro since it has some weird anti-aliasing issue on JavaFX)

**Comment by ZhangYiJiang** [comment]
Fixed by #151
