### ISSUE TITLE
Refactor styles so that stylesheets are not loaded in the TaskCard constructor 

### ISSUE THREAD

**Issue by ZhangYiJiang** [CS2103AUG2016-W10-C4/main#41]
The TaskCard styles should be loaded at the application or task list level, not on the task card objects themselves. This should improve performance and make the code cleaner.

**Comment by xdrawks** [comment]
Resolved in [60af83b](https://github.com/CS2103AUG2016-W10-C4/main/commit/60af83b63bcbef0708f5bd3f225f8a5d44e03458)
