### ISSUE TITLE
Handling of empty commands, and command with repeated \n

### ISSUE THREAD

**Issue by xdrawks** [CS2103AUG2016-W10-C4/main#64]
TodoParser will throw an error at line 84 if I repeatedly press enter at the command line with the new TextArea implementation. TodoParser should guard such commands.

**Comment by ZhangYiJiang** [comment]
This is easily done on my end (literally three lines of code), but I need `CommandResult` object to signal to UI that it should do nothing, and as of now `CommandResult` can't do that
